---
- name: Get user home directory
  shell: >
    getent passwd {{ argocd_backup_user }} | awk -F: '{ print $6 }'
  changed_when: false
  register: user_homedir
  when: argocd_backup_kubeconfig_file is not defined
  become: true

- name: Define argocd_backup_kubeconfig_file
  set_fact:
    argocd_backup_kubeconfig_file: "{{ user_homedir.stdout }}/.kube/config"
  when: argocd_backup_kubeconfig_file is not defined

- name: Create cron file
  template:
    src: argocd_backup.j2
    dest: "/etc/argocd_backup"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Copy the backup script
  copy:
    src: backup_argocd.sh
    dest: "{{ argocd_backup_script_file }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create cron file
  template:
    src: argocd-backup.j2
    dest: "{{ argocd_backup_cron_file }}"
    owner: root
    group: root
    mode: "0644"
  become: true

